#!/usr/bin/env bash

# flutter analyze
# if [ $? -ne 0 ]; then
#   exit 1
# fi

echo Testing utilities
cd $RIVE_ROOT/packages/utilities && pub run test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing coop server
cd $RIVE_ROOT/packages/coop_server && pub run test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing core
cd $RIVE_ROOT/packages/core && pub run test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing editor
cd $RIVE_ROOT/packages/editor && flutter test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing fractional
cd $RIVE_ROOT/packages/fractional && pub run test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing Rive API
cd $RIVE_ROOT/packages/rive_api && flutter test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing Rive core
cd $RIVE_ROOT/packages/rive_core && flutter test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi

echo Testing tree widget
cd $RIVE_ROOT/packages/tree_widget && flutter test && cd -
if [ $? -ne 0 ]; then
  exit 1
fi