#!/usr/bin/env bash

# flutter analyze
# if [ $? -ne 0 ]; then
#   exit 1
# fi

# Add the version number to the app
source $RIVE_ROOT/dev/write_app_version.sh
git add $RIVE_ROOT/packages/editor/lib/version.dart

cd $RIVE_ROOT
(cd dev && ./test_all.sh)