FROM google/dart

RUN apt update && apt-get -y install unzip zip

RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/flutter/bin"
RUN flutter channel master
RUN flutter doctor
RUN flutter config --enable-web

WORKDIR /app/packages/editor
ADD packages /app/packages
RUN flutter upgrade
RUN flutter pub get
RUN flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true
WORKDIR /app/packages/editor/build 
ENTRYPOINT ["mv", "web", "/output"]

