# To run this locally, use:
# docker build -f Dockerfile.web . -t test

FROM google/dart

RUN apt update && apt-get -y install unzip zip

RUN git clone https://github.com/flutter/flutter.git
ENV PATH "$PATH:/flutter/bin"

WORKDIR /app/packages/editor
ADD packages /app/packages
ADD dev /app/dev
ADD submodules /app/submodules
ADD .flutter_version /app/.flutter_version



RUN FLUTTER_ROOT=/flutter RIVE_ROOT=/app /app/dev/update_flutter.sh
# RUN flutter channel master

RUN flutter config --enable-web
RUN flutter pub get

# set up some args to use for the build, these can be set 
# when building this image using build-args
ARG sentry_dsn=https://cd4c5a674f8e44f49203ce39d47c236c@sentry.io/3876713
ARG sentry_env=development
ARG web_host=https://zuul.rive.app

RUN flutter build web \
    --dart-define=SENTRY_ENV=${sentry_env} \
    --dart-define=SENTRY_DSN=${sentry_dsn} \
    --dart-define=WEB_HOST=${web_host} \
    --dart-define=FLUTTER_WEB_USE_SKIA=true \
    --source-maps

WORKDIR /app/packages/editor/build 
ENTRYPOINT ["mv", "web", "/output"]